package be.appify.framework.weather.domain;

public enum WeatherConditionType {
	UNKNOWN,
	THUNDERSTORMS,
	CHANCE_OF_THUNDERSTORMS,
	SNOW,
	FLURRIES,
	SLEET,
	RAIN,
	CHANCE_OF_SNOW,
	CHANCE_OF_FLURRIES,
	CHANCE_OF_SLEET,
	CHANCE_OF_RAIN,
	HAZY,
	FOG,
	CLOUDY,
	MOSTLY_CLOUDY,
	PARTLY_CLOUDY,
	MOSTLY_SUNNY,
	CLEAR,
	OVERCAST
}
